package by.training.module1.command;

public enum CommandType {
    SORT_BY_VALUE_INCREASE,
    SORT_BY_VALUE_DECREASE,
    SORT_BY_WEIGHT_INCREASE,
    SORT_BY_WEIGHT_DECREASE,
    CALCULATE_VALUE,
    CALCULATE_WEIGHT,
    FIND_GEMSTONES_BY_TRANSPARENCY
}
